### ISSUE TITLE
No working on ubuntu 20.04 

### ISSUE THREAD

**Issue by blastermaster77** [derrod/legendary#46]
It installs fine but when I launch it with,  legendary auth , I get this error. 

Traceback (most recent call last):
  File "/usr/local/bin/legendary", line 11, in <module>
    load_entry_point('legendary-gl==0.0.14', 'console_scripts', 'legendary')()
  File "/usr/local/lib/python3.8/dist-packages/legendary_gl-0.0.14-py3.8.egg/legendary/cli.py", line 853, in main
  File "/usr/lib/python3.8/argparse.py", line 1380, in add_argument
    action = action_class(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'type'

**Comment by werner-mayer** [comment]
i got the same issue in 18.04
